FROM golang:1.25 AS build

COPY . /app
WORKDIR /app

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o /bootstrap ./cmd/rmu-lambda

# Create ZIP file for Lambda deployment
RUN apt-get update && apt-get install -y zip && \
    mkdir -p /lambda && \
    cd / && zip -j /lambda/function.zip /bootstrap

FROM public.ecr.aws/lambda/provided:al2
COPY --from=build /bootstrap /var/runtime/bootstrap
COPY --from=build /lambda/function.zip /lambda/function.zip
CMD [ "rmu" ]
